### ISSUE TITLE
Maintain token definitions in separate project?

### ISSUE THREAD

**Issue by georgemarrows** [jemc/ponycc#2]
I may be stepping on your toes here, but I've started a parser for Pony written in Pony over at https://github.com/georgemarrows/pony-parse. AFAICT that is not what this repo is about - it seems to be about parsing the printed AST representation from ponyc. (I'm aware you may have been working on a Pony source parser privately - if so, I've learnt some Pony and parsing tech, so nothing lost.)

Anyway, I've used a small number of tk.pony's Tk definitions and would like to use them all. 

Questions
- Should I ref this project, or does it make sense to split out the Tk defs into another repo?
- You haven't added a license file. I assume it's the same as Pony's?
- Looking to the future, would you say that ast.pony is suitable for a future Pony-in-Pony compiler, or should I target my own AST? I'm aiming for the parser framework to be generic over the AST node types in any case.

**Comment by jemc** [comment]
> I'm aware you may have been working on a Pony source parser privately

I never got very far with that as I shifted my priorities to this angle, so feel free to continue with your work, and I'm excited to see it happen!

> Looking to the future, would you say that ast.pony is suitable for a future Pony-in-Pony compiler, or should I target my own AST?

Yes, I'm aiming for this repo to be used for Pony-in-Pony compiling.  It may not yet have everything needed for that purpose, but that's the eventual goal.  Right now I'm torn about how the AST mutation is going to work to best allow parallel compilation - I'm thinking that the AST should probably end up working as a persistent data structure (which it doesn't right now), but there are some additional complications I have to work out for that.  So, in essence, the interface of `AST` may change a bit to adapt to that goal.

That said, if I were working on a Pony parser in Pony, I would want to use `pony-ast` as a dependency, using the `AST` class as a compatible exchange format between `pony-parse` and other downstream tools to be written.  You can of course do whatever you want, but I think that approach would be quite nice.

It would also solve your problem of wanting to copy the `Tk` definitions from this project - you could just depend on and `use` them instead.

> You haven't added a license file. I assume it's the same as Pony's?

Sounds like a good plan - I'll add the license file now so there will be no ambiguity.

**Comment by georgemarrows** [comment]
Ok, that sounds good, I'll carry on. Do I get the impression that this project is to allow you to start working on the compilation side without worrying about parsing? You parse the AST dump from ponyc and then (a very small 'then'!) link it up with pony-llvm?

What about parallelising compilation at the level of modules/"use"d directories? They form a DAG (I assume), so you could ripple the parsing/typechecking etc from the leaves to the main module. Of course it might limit the amount of plln at various points, depending on dependency graph width at various stages, but it should mean you can stay with a mutable AST, if that's what you want. I don't know enough to say if copy-on-write update of the AST for each pass of type-checking would make the compiler slow, but it might...

I'll depend directly on pony-ast for the moment. I'm keen for pony-parse to be used for other things besides pony-in-pony, so wouldn't want pony-ast to get too compilation focused. That's a bit down the line though ;-)

**Comment by jemc** [comment]
> Do I get the impression that this project is to allow you to start working on the compilation side without worrying about parsing? You parse the AST dump from ponyc and then (a very small 'then'!) link it up with pony-llvm?

Yeah, that's the general idea.  But if you get `pony-parse` up and running, it will probably make some things easier on this end, since I can use `pony-parse` instead of invoking `ponyc` in a subprocess and capturing/parsing the stdout.

 > What about parallelising compilation at the level of modules/"use"d directories? They form a DAG (I assume), so you could ripple the parsing/typechecking etc from the leaves to the main module. Of course it might limit the amount of plln at various points, depending on dependency graph width at various stages, but it should mean you can stay with a mutable AST, if that's what you want. I don't know enough to say if copy-on-write update of the AST for each pass of type-checking would make the compiler slow, but it might...

Yes, this is another option I'm considering.  However, most of the later stages of the `ponyc` compiler as its currently written end up operating on the entire AST as a whole so that types in other packages can be referenced, etc.  So I'd have to either accept that those stages can't be parallelized, or figure out a way to refactor them so that they can be.  Either way, at least getting the preliminary stages parallelized (starting with parsing, etc) would be a win.

> I'll depend directly on pony-ast for the moment. I'm keen for pony-parse to be used for other things besides pony-in-pony, so wouldn't want pony-ast to get too compilation focused.

Definitely let me know if I make a change that causes problems for you downstream, and we'll see if we can work through it to something that works well on both sides.

**Comment by jemc** [comment]
A lot has changed since this discussion, so I don't think this ticket is necessarily worth keeping open anymore.  A summary of the changes:

- AST definitions are now statically typed data structures instead of "dynamic"-style type-unaware trees.
- A parser and printer are now included in this repo, as subpackages of the `ast` package (`ast/parse` and `ast/print`).
- This repo has been renamed from `pony-ast` to `ponycc`, and repositioned as the single repo for work on a Pony compiler. This was done for practical purposes, as it's easier to do large-scale coordinated changes on a single repo. The `ast` package is now a subpackage of the `ponycc` package, but it will remain decoupled enough that it can be used independently from the rest of the compiler, including by other tools that wish to use it.
